Aula 5

In [ ]:
# parenteses = tupla
# colchete = lista

In [2]:
import numpy as np
import matplotlib as plt

In [3]:
frutas = np.array(['banana','bergamota','uva','abacaxi'])

for fruta in frutas:
  print(fruta)

banana
bergamota
uva
abacaxi


In [5]:
a = np.array([1,3,5,12,17,524]) #matriz
b = [1,3,5,12,17,524] #lista

print(b*3)
print(a*3)

[1, 3, 5, 12, 17, 524, 1, 3, 5, 12, 17, 524, 1, 3, 5, 12, 17, 524]
[   3    9   15   36   51 1572]


In [6]:
m = [[10,20],[30,40]]

print(m[1][0])

30


In [8]:
m = np.array([[10,20],[30,40]])

print(m[1,0])

30


In [18]:
m = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

print(m[1,0])
print(m[1,0,1])
print(m.shape)
print(len(m.shape))

[50 60]
60
(2, 2, 2)
3


In [17]:
m1 = np.random.random((2,2,3))
m2 = np.random.random((4,2))
m3 = np.random.random((8,5))

print(m3)
print(m3[1,2:4]) #intervalo 2 ao 4

[[0.06015317 0.35779435 0.20152063 0.64703509 0.45591501]
 [0.54920485 0.4584674  0.78640211 0.20120782 0.30173404]
 [0.30469889 0.05407285 0.06734106 0.33994119 0.04213351]
 [0.21917807 0.971331   0.0124223  0.42578257 0.34698131]
 [0.08221112 0.35537786 0.70859043 0.69699352 0.6025044 ]
 [0.62447132 0.24640358 0.07531278 0.40402183 0.7099423 ]
 [0.17685692 0.27437872 0.88406877 0.91302364 0.17442578]
 [0.74655407 0.10986465 0.5039701  0.89835804 0.4524755 ]]
[0.78640211 0.20120782]


In [21]:
m4 = np.random.random((8,5)) #matriz 8x5
print(m4)

m4[1,1:4] = np.array([10,100,100]) #na linha 1 de m4, substitui os elementos de 1 a 4
print(m4)

[[0.48452024 0.56493211 0.34917354 0.82306489 0.51189285]
 [0.58099083 0.15898278 0.45693911 0.16365153 0.55464173]
 [0.10789283 0.34622962 0.58307058 0.38450747 0.41471946]
 [0.34029164 0.69394849 0.56211557 0.76382454 0.94384502]
 [0.07055877 0.43071399 0.37685378 0.51351693 0.01926962]
 [0.33318423 0.69547775 0.49415339 0.00614496 0.25160066]
 [0.8085411  0.34987864 0.26390226 0.26055283 0.75660262]
 [0.61018104 0.93048392 0.73335837 0.24007261 0.80606455]]
[[4.84520241e-01 5.64932110e-01 3.49173543e-01 8.23064888e-01
  5.11892848e-01]
 [5.80990825e-01 1.00000000e+01 1.00000000e+02 1.00000000e+02
  5.54641726e-01]
 [1.07892827e-01 3.46229620e-01 5.83070582e-01 3.84507473e-01
  4.14719465e-01]
 [3.40291639e-01 6.93948487e-01 5.62115571e-01 7.63824536e-01
  9.43845020e-01]
 [7.05587706e-02 4.30713990e-01 3.76853781e-01 5.13516931e-01
  1.92696234e-02]
 [3.33184233e-01 6.95477746e-01 4.94153393e-01 6.14496063e-03
  2.51600663e-01]
 [8.08541095e-01 3.49878644e-01 2.63902262e-01 2.605528