In [1]:
import numpy as np

t = ['a','b','c','d','e','f']
#nenhum printa o ultimo, n-1
print(t)
print(t[1:3]) #1 até 3, nao printa o ultimo
print(t[:4])
print(t[3:])
print(t[:])
t[1:3] = ['x','y']
print(t)
t.append('g') #inserir elemento na lista
print(t)

['a', 'b', 'c', 'd', 'e', 'f']
['b', 'c']
['a', 'b', 'c', 'd']
['d', 'e', 'f']
['a', 'b', 'c', 'd', 'e', 'f']
['a', 'x', 'y', 'd', 'e', 'f']
['a', 'x', 'y', 'd', 'e', 'f', 'g']


In [3]:
t1 = ['a','b','c']
t2 = ['d','p']

t1.extend(t2)
print(t1)

['a', 'b', 'c', 'd', 'p']


In [ ]:
t = ['d','e','a','c','b']
print(t)
t.sort()
print(t)


In [ ]:
t=['a','b','c']
print(t)
x = t.pop(1)
print(t)

In [ ]:
t = ['a','b','c']
print(t)
del t[1]
print(t)

In [ ]:
t = ['a','b','c']
print(t)
t.remove('b')
print(t)

In [ ]:
eng2pt = dict()
print(eng2pt)
eng2pt['one'] = 'um'
print(eng2pt)

In [2]:
eng2pt = dict()
eng2pt = {'one':'um','two':'dois','three':'tres'}
print(eng2pt)
print(len(eng2pt))

{'one': 'um', 'two': 'dois', 'three': 'tres'}
3


In [4]:
word = 'brontosaurus'
d = dict()

for c in word:
  if c not in d:
    d[c] = 1
  else:
    d[c]=d[c]+1

print(d)

In [8]:
a2 = np.random.randint(10,20)
print(a2)

10


In [9]:
frutas1 = ['abacaxi','laranja','bergamota','uva']
np.random.choice(frutas1) #imprime um elemento aleatorio

'uva'

In [14]:
a = np.random.random((4,5))
print(a)
b = np.sum(a) #soma os elementos de a
print(b)
c = np.max(a) #printa o maior elemento
print(c)
d = np.min(a) #printa o menor elemento
print(d)

[[0.78759957 0.43923678 0.71895465 0.04329367 0.08201269]
 [0.17198675 0.56126757 0.23242305 0.91861681 0.07753139]
 [0.17064419 0.80144604 0.77640073 0.11590838 0.27868986]
 [0.2741527  0.96354158 0.46944953 0.23098183 0.05291372]]
8.167051506632966
0.9635415792743086
0.04329367360189562


In [15]:
a1 = np.random.random((4,5))
print(a1)
np.sum(a1,axis=0) #soma todos elementos de cada coluna

[[0.12925691 0.63464454 0.69742453 0.7468021  0.46925964]
 [0.73910091 0.49734335 0.07901127 0.26771823 0.65871774]
 [0.15487718 0.21451351 0.69675529 0.77403372 0.74812727]
 [0.17766257 0.87007974 0.64795826 0.50436535 0.71318402]]


array([1.20089757, 2.21658114, 2.12114935, 2.2929194 , 2.58928867])

In [18]:
v1 = np.array([1,2,3,4])
v2 = np.array([-1,-2,-3,-4])
v1*v2 #multiplica  elemento por elemento


array([ -1,  -4,  -9, -16])

In [19]:

np.dot(v1,v2) #produto escalar

-30

In [22]:
class Quadrado: #define a classe
  lado=0        #atributo

q1 = Quadrado()
print(q1.lado)
q1.lado=10
print(q1.lado)

q2 = Quadrado()
q2.lado = 50
print(q2.lado)

0
10
50


In [29]:
class Quadrado:
  lado=0

def area(lado): #define a funcao
  return lado**2 ####lado ao quadrado

q2 = Quadrado() #cria objeto
q2.lado = 7 

print(area(q2.lado))


49


In [30]:
class Quadrado:
  lado = 0
  def area(self): #funcao faz parte da classe Quadrado
    return self.lado**2

q1 = Quadrado()
q2 = Quadrado()

q1.lado = 3
q2.lado = 4

print(q1.area())
print(q2.area())

9
16
